STOP_SUBPROCESS_MESSAGE = "stop subprocess"
SERVER_WINDOW_NAME = "MY SERVER"
SCRIPT_NAME_SUFFIX = "my_"

SUBPROCESSES = {
    SCRIPT_NAME_SUFFIX + 'shop_watcher': 59000,
    SCRIPT_NAME_SUFFIX + 'pregame_phase_detector': 59001
}
